# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

loki:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/loki-fips
    tag: 3.4.3
gateway:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/nginx-fips
    tag: 1.27.5
memcached:
  image:
    repository: cgr.dev/du-uds-defenseunicorns/memcached-fips
    tag: 1.6.38
