# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

loki:
  image:
    registry: quay.io
    repository: rfcurated/grafana/loki
    tag: 3.6.2-jammy-fips-rfcurated-rfhardened
gateway:
  image:
    registry: quay.io
    repository: rfcurated/nginx
    tag: 1.29.3-slim-jammy-fips-rfcurated-rfhardened
memcached:
  image:
    repository: quay.io/rfcurated/memcached
    tag: 1.6.39-jammy-fips-rfcurated-rfhardened
sidecar:
  image:
    repository: quay.io/rfcurated/k8s-sidecar
    tag: 1.30.10-jammy-scratch-fips-rfcurated-rfhardened
