loki:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/loki
    tag: 3.1.1
gateway:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/nginx-fips
    tag: 1.27.1
memcached:
  image:
    repository: cgr.dev/du-uds-defenseunicorns/memcached
    tag: 1.6.31
