loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.2.0

gateway:
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.27-alpine

memcached:
  image:
    registry: docker.io
    repository: memcached
    tag: 1.6.31-alpine
