# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.6.3

gateway:
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.29-alpine

memcached:
  image:
    registry: docker.io
    repository: memcached
    tag: 1.6.40-alpine

sidecar:
  image:
    repository: ghcr.io/kiwigrid/k8s-sidecar
    tag: 2.2.3
