# Overwritten by ci-iac-aws package
options:
  architecture: amd64

variables:
  core:
    loki_chunks_bucket: ${ZARF_VAR_LOKI_S3_BUCKET}
    loki_ruler_bucket: ${ZARF_VAR_LOKI_S3_BUCKET}
    loki_admin_bucket: ${ZARF_VAR_LOKI_S3_BUCKET}
    loki_s3_region: ${ZARF_VAR_LOKI_S3_AWS_REGION}
    loki_irsa_annotation: ${ZARF_VAR_LOKI_S3_ROLE_ARN}
    velero_use_secret: false
    velero_irsa_annotation: "${ZARF_VAR_VELERO_S3_ROLE_ARN}"
    velero_bucket: ${ZARF_VAR_VELERO_S3_BUCKET}
    velero_bucket_region: ${ZARF_VAR_VELERO_S3_AWS_REGION}
    velero_bucket_provider_url: ""
    velero_bucket_credential_name: ""
    velero_bucket_credential_key: ""
    grafana_ha: true
    grafana_pg_host: ${ZARF_VAR_GRAFANA_PG_HOST}
    grafana_pg_port: ${ZARF_VAR_GRAFANA_PG_PORT}
    grafana_pg_database: ${ZARF_VAR_GRAFANA_PG_DATABASE}
    grafana_pg_password: ${ZARF_VAR_GRAFANA_PG_PASSWORD}
    grafana_pg_user: ${ZARF_VAR_GRAFANA_PG_USER}
