# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: registry1.dso.mil
  repository: ironbank/opensource/falcosecurity/falco
  tag: 0.43.0
  pullPolicy: IfNotPresent

falcosidekick:
  image:
    registry: registry1.dso.mil
    repository: ironbank/opensource/falcosecurity/falcosidekick
    tag: 2.32.0
    pullPolicy: IfNotPresent
