# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.autoscaling.sessionStickiness.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "keycloak.fullname" . }}-sticky-session
spec:
  host: {{ include "keycloak.fullname" . }}-http.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ include "keycloak.fullname" . }}-session
          ttl: 0s
{{- end }}
