# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: registry1.dso.mil/ironbank/istio-ecosystem/authservice
  tag: "1.1.5-fips"
