leastPrivilege: false

exporter:
  enabled: true
  # Disable serviceMonitor to handle standalone testing, handled by UDS Package
  serviceMonitor:
    enabled: false
  apiSvc: neuvector-svc-controller-api:10443
  svc:
    # Temporary disabling of service to allow adding appProtocol via custom service in the config chart
    enabled: false
    type: ClusterIP
