apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: authservice
  namespace: {{ .Release.Namespace }}
spec:
  network:
    allow:
      # Permit intra-namespace communication for multi-replica setup
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      # Egress must be allowed to the external facing Keycloak endpoint
      - direction: Egress
        remoteGenerated: Anywhere
        description: "SSO Provider"
