image:
  registry: cgr.dev
  repository: du-uds-defenseunicorns/promtail
  tag: 3.1.0
sidecar:
  configReloader:
    image:
      registry: cgr.dev
      repository: du-uds-defenseunicorns/configmap-reload-fips
      tag: 0.12.0
