# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: quay.io/rfcurated/vector
  tag: 0.53.0-jammy-fips-rfcurated-rfhardened
