# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v2
name: blackbox-exporter
description: Prometheus Blackbox Exporter for UDS Core

type: application

version: 0.1.0
appVersion: v0.28.0
