# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: registry1.dso.mil
  repository: ironbank/opensource/grafana/grafana
  tag: 12.0.1

initChownData:
  image:
    registry: registry1.dso.mil
    repository: ironbank/redhat/ubi/ubi9-minimal
    tag: 9.6

downloadDashboardsImage:
  registry: registry1.dso.mil
  repository: ironbank/redhat/ubi/ubi9-minimal
  tag: 9.6

sidecar:
  image:
    registry: registry1.dso.mil
    repository: ironbank/kiwigrid/k8s-sidecar
    tag: 1.30.3
