image:
  registry: registry1.dso.mil
  repository: ironbank/opensource/grafana/grafana
  tag: 10.3.1

initChownData:
  image:
    registry: registry1.dso.mil
    repository: ironbank/redhat/ubi/ubi9-minimal
    tag: 9.3

downloadDashboardsImage:
  registry: registry1.dso.mil
  repository: ironbank/redhat/ubi/ubi9-minimal
  tag: 9.3

sidecar:
  image:
    registry: registry1.dso.mil
    repository: ironbank/kiwigrid/k8s-sidecar
    tag: 1.25.3
