# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: quay.io
  repository: rfcurated/grafana
  tag: 12.3.2-jammy-scratch-fips-rfcurated

initChownData:
  image:
    registry: quay.io
    repository: rfcurated/busybox
    tag: 1.37.0-musl-rf.1-fips-rfcurated

downloadDashboardsImage:
  registry: quay.io
  repository: rfcurated/curl
  tag: 8.18.0-jammy-scratch-fips-rfcurated

sidecar:
  image:
    registry: quay.io
    repository: rfcurated/kiwigrid/k8s-sidecar
    tag: 2.5.0-jammy-scratch-fips-rfcurated-rfhardened
