sidecar:
  image:
    # -- The Docker registry
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.27.6

image:
  registry: docker.io
  repository: grafana/grafana
  tag: 11.2.0

initChownData:
  image:
    registry: docker.io
    repository: library/busybox
    tag: 1.36.1

downloadDashboardsImage:
  registry: docker.io
  repository: curlimages/curl
  tag: 8.10.1
