sidecar:
  image:
    # -- The Docker registry
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.27.4

image:
  registry: docker.io
  repository: grafana/grafana
  tag: 11.1.0

initChownData:
  image:
    registry: docker.io
    repository: library/busybox
    tag: 1.36.1

downloadDashboardsImage:
  registry: docker.io
  repository: curlimages/curl
  tag: 8.8.0
