# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Check CA Cert Updates

on:
  schedule:
    # Runs every morning at 2:00 AM UTC
    - cron: "0 2 * * *"
  pull_request:
    branches: [main]
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, edited, synchronize]
    paths:
      - "certs/**"
      - "src/pepr/uds-operator-config/templates/uds-ca-certs.yaml"
      - ".github/workflows/check-ca-certs.yaml"

permissions:
  contents: read

jobs:
  test-ca-certs:
    runs-on: ubuntu-latest
    name: check-certs
    permissions:
      contents: read
      packages: read
    env:
      SHA: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          rapidfortUsername: ${{ secrets.RAPIDFORT_USERNAME }}
          rapidfortPassword: ${{ secrets.RAPIDFORT_PASSWORD }}

      - name: Install script dependencies
        run: npm ci
        working-directory: scripts/root-ca-retriever

      - name: Check CA Certs for Updates
        run:
          uds run check-ca-certs

      - name: Send Slack notification
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/slack-alert
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ vars.SLACK_ALERT_CHANNEL }}
