# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# This workflow runs a Lula scan against the PR to see if compliance has changed

name: Lula Scan

on:
  pull_request:
    branches: ["main"]
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    # labeled is added to support renovate-ready labelling on PRs
    types: [milestoned, labeled, opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:
  scan-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - name: Use Node.js 22
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          cache: "npm"
      - name: Run Lula Scan
        run: |
          # renovate: datasource=github-tags depName=defenseunicorns/lula versioning=semver
          npx --yes lula2@0.7.1 crawl
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
