# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Backports

# This workflow is triggered on pull requests targeting release/*
on:
  pull_request:
    branches: ["release/**"]
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    # labeled is added to support renovate-ready labelling on PRs
    types: [milestoned, labeled, opened, reopened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  id-token: write # Needed for OIDC-related operations.
  contents: read # Allows reading the content of the repository.
  pull-requests: write # Allows writing pull request metadata.
  packages: read # Allows reading the published GHCR packages

# Default settings for all run commands in the workflow jobs.
defaults:
  run:
    shell: bash -e -o pipefail {0}

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: lint-check
        uses: ./.github/actions/lint-check

  autogenerated-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: autogenerated-check
        uses: ./.github/actions/autogenerated-check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: unit-tests
        uses: ./.github/actions/unit-tests

  # Full CI for Release PRs created by release-please (detect by head ref prefix)
  run-package-test-full:
    needs: [lint-check, autogenerated-check, unit-tests]
    if: ${{ startsWith(github.head_ref, 'release-please--') }}
    name: Schedule
    strategy:
      matrix:
        package: [all]
        flavor: [upstream]
        test_type: [install, upgrade]
    uses: ./.github/workflows/test.yaml
    with:
      package: ${{ matrix.package }}
      flavor: ${{ matrix.flavor }}
      test_type: ${{ matrix.test_type }}
      target_version: ${{ github.base_ref }}
    secrets: inherit

  # Shim out required heavy tests for all PRs to release/*
  run-package-test-shim:
    needs: [lint-check, autogenerated-check, unit-tests]
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    name: Schedule
    strategy:
      matrix:
        package: [all]
        flavor: [upstream]
        test_type: [install, upgrade]
    uses: ./.github/workflows/test-shim.yaml
    with:
      package: ${{ matrix.package }}
      flavor: ${{ matrix.flavor }}
      test_type: ${{ matrix.test_type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
