# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  core:
    # Keycloak variables
    keycloak_ha: true
    keycloak_pg_username: postgres
    keycloak_pg_password: unicorn123!@#UN
    keycloak_pg_database: keycloak
    keycloak_pg_host: host.k3d.internal
    keycloak_devmode: false

    # Grafana variables
    grafana_ha: true
    grafana_pg_host: host.k3d.internal
    grafana_pg_port: 5432
    grafana_pg_database: grafana
    grafana_pg_password: unicorn123!@#UN
    grafana_pg_user: postgres
    grafana_pg_ssl_mode: disable

    # Authservice variables
    AUTHSERVICE_REDIS_URI: redis://authservice:authservice@host.k3d.internal:6379
    AUTHSERVICE_REPLICA_COUNT: 2
