pilot:
  image: registry1.dso.mil/ironbank/tetrate/istio/pilot:1.20.1-tetratefips-v0
global:
  proxy_init:
    image: registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.20.1-tetratefips-v0
  proxy:
    image: registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.20.1-tetratefips-v0
