pilot:
  image: "cgr.dev/du-uds-defenseunicorns/istio-pilot-fips:1.23.2"
global:
  proxy_init:
    # renovate: image=cgr.dev/du-uds-defenseunicorns/istio-proxy-fips
    image: "###ZARF_REGISTRY###/du-uds-defenseunicorns/istio-proxy-fips:1.23.2"
  proxy:
    # renovate: image=cgr.dev/du-uds-defenseunicorns/istio-proxy-fips
    image: "###ZARF_REGISTRY###/du-uds-defenseunicorns/istio-proxy-fips:1.23.2"
