pilot:
  image: "docker.io/istio/pilot:1.22.2-distroless"
global:
  proxy_init:
    # renovate: image=docker.io/istio/proxyv2
    image: "###ZARF_REGISTRY###/istio/proxyv2:1.22.2-distroless"
  proxy:
    # renovate: image=docker.io/istio/proxyv2
    image: "###ZARF_REGISTRY###/istio/proxyv2:1.22.2-distroless"
